filter:
    excluded_paths:
        - "tests/"
        - "vendor/"

tools:
    external_code_coverage:
        timeout: 600
        runs: 1

build:
    environment:
        php: 7.1.3
        mysql: true
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
