filter:
    paths: ["src/*"]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 1

build:
    tests:
        override:
            command: "php -v"
    environment:
        php: 7.2
        mysql: true
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
