filter:
    paths: ["src/*"]

tools:
    external_code_coverage:
        timeout: 600
        runs: 1

build:
    environment:
        php: 7.2
        mysql: true
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
